// ==========================================
// DUNGEON FORECAST DATABASE
// Source: Narakia et Vicky Zweistein
// Range: 26/12/2025 to 19/02/2026
// ==========================================

const FORECAST_DB = {
  "26/12/2025": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "Lunar Altar" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Ow El Dungeon" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "The Hill Hazize" },
    { type: "Modulox 51 - 95", name: "Miseryum" },
    { type: "Modulox 96 - 140", name: "Magik Riktus Den" },
    { type: "Modulox 141 - 185", name: "Enurado Dungeon" },
    { type: "Modulox 186 - 230", name: "Plantiguard Dungeon" },
  ],
  "27/12/2025": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "Sureberry Fields" },
    { type: "Modulox 51 - 95", name: "Mollusky Dungeon" },
    { type: "Modulox 96 - 140", name: "Tormentor Pit" },
    { type: "Modulox 141 - 185", name: "The Stalagmotel" },
    { type: "Modulox 186 - 230", name: "Destroyer Dungeon" },
  ],
  "28/12/2025": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Morbax Neplopolis" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "Deathburn Dungeon" },
    { type: "Modulox 51 - 95", name: "Abandoned Strichery" },
    { type: "Modulox 96 - 140", name: "Flaxhid's Sanctuary" },
    { type: "Modulox 141 - 185", name: "Abandoned Cawwot Stowewoom" },
    { type: "Modulox 186 - 230", name: "Phytomorph Dungeon" },
  ],
  "29/12/2025": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Iced-Over Crest" },
    { type: "DJ 201 - 215", name: "Tundrazor Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Larventura" },
    { type: "Modulox 51 - 95", name: "Morbax Neplopolis" },
    { type: "Modulox 96 - 140", name: "Hushquarters" },
    { type: "Modulox 141 - 185", name: "The Villainy Vineyards" },
    { type: "Modulox 186 - 230", name: "The Minerall Tower (lvl 200)" },
  ],
  "30/12/2025": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "The Forgotten Lair" },
    { type: "DJ 66 - 80", name: "The Ratatombs" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Or'Hodruin Volcano" },
    { type: "DJ 201 - 215", name: "Sunsloth Dungeon" },
    { type: "DJ 216 - 230", name: "Voidivion Dungeon" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "The Mineral Tower" },
    { type: "Modulox 51 - 95", name: "The Forgotten Lair" },
    { type: "Modulox 96 - 140", name: "Kween's Gawden" },
    { type: "Modulox 141 - 185", name: "Wa Wabbit's Castle" },
    { type: "Modulox 186 - 230", name: "Sunsloth Dungeon" },
  ],
  "31/12/2025": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "Abandoned Scarapit" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "The Frozen Tower" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Sandyoptera Mother-Hive" },
    { type: "DJ 156 - 170", name: "Ow El Dungeon" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "Octopus Crew Dungeon" },
    { type: "Modulox 51 - 95", name: "Wagnar's Castle" },
    { type: "Modulox 96 - 140", name: "Ambassador's Wing" },
    { type: "Modulox 141 - 185", name: "Sandyoptera Mother-Hive" },
    { type: "Modulox 186 - 230", name: "Crabstacean Dungeon" },
  ],
  "01/01/2026": [
    { type: "DJ 6 - 20", name: "??" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Abandoned Strichery" },
    { type: "DJ 81 - 95", name: "Miseryum" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Treechnid Dungeon" },
    { type: "DJ 141 - 155", name: "Enurado Dungeon" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "The Hill Hazize" },
    { type: "Modulox 51 - 95", name: "Boarthroom Estate" },
    { type: "Modulox 96 - 140", name: "Blackspore Dungeon" },
    { type: "Modulox 141 - 185", name: "Kannivore Dungeon" },
    { type: "Modulox 186 - 230", name: "Pingwin Dungeon" },
  ],
  "02/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "Wellspring of Evil" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "Hoola Hoopiwi" },
    { type: "Modulox 51 - 95", name: "Cro-Cave" },
    { type: "Modulox 96 - 140", name: "The Snaptrap" },
    { type: "Modulox 141 - 185", name: "Kanniball Dungeon" },
    { type: "Modulox 186 - 230", name: "Sunsloth Dungeon" },
  ],
  "03/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Cwab's Castle" },
    { type: "DJ 66 - 80", name: "Lunar Altar" },
    { type: "DJ 81 - 95", name: "Schnekymosis Cavern" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "The Frozen Tower" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "The Minerall Tower (lvl 200)" },
    { type: "DJ 201 - 215", name: "Scramshell Dungeon" },
    { type: "DJ 216 - 230", name: "Destroyer Dungeon" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "The Tofuhouse" },
    { type: "Modulox 51 - 95", name: "Abandoned Strichery" },
    { type: "Modulox 96 - 140", name: "Treechnid Dungeon" },
    { type: "Modulox 141 - 185", name: "Kali's Lair" },
    { type: "Modulox 186 - 230", name: "Horridemon Dungeon" },
  ],
  "04/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "The Ratatombs" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "Puddly Dungeon" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "Gobball Pastures" },
    { type: "Modulox 51 - 95", name: "Kokokobana" },
    { type: "Modulox 96 - 140", name: "Dirty Trouffe Estate" },
    { type: "Modulox 141 - 185", name: "Wellspring of Evil" },
    { type: "Modulox 186 - 230", name: "Abyssal Creeper Dungeon" },
  ],
  "05/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "The Forgotten Lair" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Morbax Neplopolis" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "Ambassador's Wing" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Or'Hodruin Volcano" },
    { type: "DJ 201 - 215", name: "Sunsloth Dungeon" },
    { type: "DJ 216 - 230", name: "Voidivion Dungeon" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "Sureberry Fields" },
    { type: "Modulox 51 - 95", name: "Abandoned Scarapit" },
    { type: "Modulox 96 - 140", name: "Hushquarters" },
    { type: "Modulox 141 - 185", name: "The Stalagmotel" },
    { type: "Modulox 186 - 230", name: "Voidivion Dungeon" },
  ],
  "06/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "Sandyoptera Mother-Hive" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "Larventura" },
    { type: "Modulox 51 - 95", name: "Lunar Altar" },
    { type: "Modulox 96 - 140", name: "Magik Riktus Den" },
    { type: "Modulox 141 - 185", name: "Elite Riktus Dungeon" },
    { type: "Modulox 186 - 230", name: "Horridemon Dungeon" },
  ],
  "07/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Iced-Over Crest" },
    { type: "DJ 201 - 215", name: "Tundrazor Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "The Tofuhouse" },
    { type: "Modulox 51 - 95", name: "Dry Selachii" },
    { type: "Modulox 96 - 140", name: "Moowolf's Lair" },
    { type: "Modulox 141 - 185", name: "Gerbean Dungeon" },
    { type: "Modulox 186 - 230", name: "Phytomorph Dungeon" },
  ],
  "08/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Cwab's Castle" },
    { type: "DJ 66 - 80", name: "Abandoned Strichery" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "The Minerall Tower (lvl 200)" },
    { type: "DJ 201 - 215", name: "Scramshell Dungeon" },
    { type: "DJ 216 - 230", name: "Destroyer Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "Octopus Crew Dungeon" },
    { type: "Modulox 51 - 95", name: "Temple of the Grand Orrok" },
    { type: "Modulox 96 - 140", name: "Lenald Empelol's Temple" },
    { type: "Modulox 141 - 185", name: "Wellspring of Evil" },
    { type: "Modulox 186 - 230", name: "Iced-Over Crest" },
  ],
  "09/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "Ambassador's Wing" },
    { type: "DJ 126 - 140", name: "Treechnid Dungeon" },
    { type: "DJ 141 - 155", name: "Enurado Dungeon" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Hoola Hoopiwi" },
    { type: "Modulox 51 - 95", name: "Bwork Dungeon" },
    { type: "Modulox 96 - 140", name: "The Whirlway Station" },
    { type: "Modulox 141 - 185", name: "Ow El Dungeon" },
    { type: "Modulox 186 - 230", name: "Vandalophrenic Dungeon" },
  ],
  "10/01/2026": [
    { type: "DJ 6 - 20", name: "??" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Miseryum" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "Wellspring of Evil" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "The Royal Pasturizer" },
    { type: "Modulox 51 - 95", name: "Mussly Hammam" },
    { type: "Modulox 96 - 140", name: "Hagen Daz's Pot" },
    { type: "Modulox 141 - 185", name: "Bistrogue" },
    { type: "Modulox 186 - 230", name: "The Mineral Tower (lvl 215)" },
  ],
  "11/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "Abandoned Scarapit" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "Puddly Dungeon" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "The Mineral Tower" },
    { type: "Modulox 51 - 95", name: "Arachnee Dungeon" },
    { type: "Modulox 96 - 140", name: "Flaxhid's Sanctuary" },
    { type: "Modulox 141 - 185", name: "Mecha Factory" },
    { type: "Modulox 186 - 230", name: "Abyssal Creeper Dungeon" },
  ],
  "12/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Sureberry Fields" },
    { type: "Modulox 51 - 95", name: "Tsu's Palace" },
    { type: "Modulox 96 - 140", name: "Jelly Dungeon" },
    { type: "Modulox 141 - 185", name: "Wa Wabbit's Castle" },
    { type: "Modulox 186 - 230", name: "Streye Dungeon?" },
  ],
  "13/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "Schnekymosis Cavern" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "Deathburn Dungeon" },
    { type: "Modulox 51 - 95", name: "Cwab's Castle" },
    { type: "Modulox 96 - 140", name: "Castuc Dungeon" },
    { type: "Modulox 141 - 185", name: "The Villainy Vineyards" },
    { type: "Modulox 186 - 230", name: "Pingwin Dungeon" },
  ],
  "14/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Morbax Neplopolis" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "The Royal Pasturizer" },
    { type: "Modulox 51 - 95", name: "The Undieworld" },
    { type: "Modulox 96 - 140", name: "The Horned Glacier" },
    { type: "Modulox 141 - 185", name: "Enurado Dungeon" },
    { type: "Modulox 186 - 230", name: "Horridemon Dungeon" },
  ],
  "15/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "Treechnee Dungeon" },
    { type: "Modulox 51 - 95", name: "The Ratatombs" },
    { type: "Modulox 96 - 140", name: "Kween's Gawden" },
    { type: "Modulox 141 - 185", name: "Forbidden City" },
    { type: "Modulox 186 - 230", name: "The Mineral Tower (lvl 215)" },
  ],
  "16/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Lunar Altar" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "The Frozen Tower" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "Enurado Dungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Iced-Over Crest" },
    { type: "DJ 201 - 215", name: "Tundrazor Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "The Raised Vault" },
    { type: "Modulox 51 - 95", name: "Bitter-Hammer Dungeon" },
    { type: "Modulox 96 - 140", name: "Jelly Dungeon" },
    { type: "Modulox 141 - 185", name: "Kannivore Dungeon" },
    { type: "Modulox 186 - 230", name: "Dreggons' Sanctuary" },
  ],
  "17/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "The Forgotten Lair" },
    { type: "DJ 66 - 80", name: "Abandoned Strichery" },
    { type: "DJ 81 - 95", name: "Abandoned Scarapit" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "Ambassador's Wing" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "Sandyoptera Mother-Hive" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Or'Hodruin Volcano" },
    { type: "DJ 201 - 215", name: "Sunsloth Dungeon" },
    { type: "DJ 216 - 230", name: "Voidivion Dungeon" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "The Hill Hazize" },
    { type: "Modulox 51 - 95", name: "Mollusky Dungeon" },
    { type: "Modulox 96 - 140", name: "The Snaptrap" },
    { type: "Modulox 141 - 185", name: "Abandoned Cawwot Stowewoom" },
    { type: "Modulox 186 - 230", name: "Pingwin Dungeon" },
  ],
  "18/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Cwab's Castle" },
    { type: "DJ 66 - 80", name: "The Ratatombs" },
    { type: "DJ 81 - 95", name: "Miseryum" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "Puddly Dungeon" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Wellspring of Evil" },
    { type: "DJ 156 - 170", name: "Bistrogue" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "The Minerall Tower (lvl 200)" },
    { type: "DJ 201 - 215", name: "Scramshell Dungeon" },
    { type: "DJ 216 - 230", name: "Destroyer Dungeon" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "Sureberry Fields" },
    { type: "Modulox 51 - 95", name: "Miseryum" },
    { type: "Modulox 96 - 140", name: "Tormentor Pit" },
    { type: "Modulox 141 - 185", name: "Crocodyl Dungeon" },
    { type: "Modulox 186 - 230", name: "Tundrazor Dungeon" },
  ],
  "19/01/2026": [
    { type: "DJ 6 - 20", name: "??" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "Lunar Altar" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Ow El Dungeon" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "Deathburn Dungeon" },
    { type: "Modulox 51 - 95", name: "Cro-Cave" },
    { type: "Modulox 96 - 140", name: "Blackspore Dungeon" },
    { type: "Modulox 141 - 185", name: "Tropickle Dungeon" },
    { type: "Modulox 186 - 230", name: "Dreggons' Sanctuary" },
  ],
  "20/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "Schnekymosis Cavern" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "Larventura" },
    { type: "Modulox 51 - 95", name: "Bwork Dungeon" },
    { type: "Modulox 96 - 140", name: "Puddly Dungeon" },
    { type: "Modulox 141 - 185", name: "SrambadDungeon" },
    { type: "Modulox 186 - 230", name: "Badgeroxes' Lair" },
  ],
  "21/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Treechnid Dungeon" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "The Mineral Tower" },
    { type: "Modulox 51 - 95", name: "Wagnar's Castle" },
    { type: "Modulox 96 - 140", name: "Lenald Empelol's Temple" },
    { type: "Modulox 141 - 185", name: "Blopera" },
    { type: "Modulox 186 - 230", name: "Necroworld" },
  ],
  "22/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "Morbax Neplopolis" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "Sandyoptera Mother-Hive" },
    { type: "DJ 156 - 170", name: "Bistrogue" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Iced-Over Crest" },
    { type: "DJ 201 - 215", name: "Tundrazor Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "Octopus Crew Dungeon" },
    { type: "Modulox 51 - 95", name: "Boarthroom Estate" },
    { type: "Modulox 96 - 140", name: "Ambassador's Wing" },
    { type: "Modulox 141 - 185", name: "Kanniball Dungeon" },
    { type: "Modulox 186 - 230", name: "Destroyer Dungeon" },
  ],
  "23/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "The Forgotten Lair" },
    { type: "DJ 66 - 80", name: "The Ratatombs" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Or'Hodruin Volcano" },
    { type: "DJ 201 - 215", name: "Sunsloth Dungeon" },
    { type: "DJ 216 - 230", name: "Voidivion Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "The Hill Hazize" },
    { type: "Modulox 51 - 95", name: "Bitter-Hammer Dungeon" },
    { type: "Modulox 96 - 140", name: "Moowolf's Lair" },
    { type: "Modulox 141 - 185", name: "Elite Riktus Dungeon" },
    { type: "Modulox 186 - 230", name: "Vandalophrenic Dungeon" },
  ],
  "24/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "The Frozen Tower" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Ow El Dungeon" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "Hoola Hoopiwi" },
    { type: "Modulox 51 - 95", name: "The Forgotten Lair" },
    { type: "Modulox 96 - 140", name: "Treechnid Dungeon" },
    { type: "Modulox 141 - 185", name: "Gerbean Dungeon" },
    { type: "Modulox 186 - 230", name: "Plantiguard Dungeon" },
  ],
  "25/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Abandoned Strichery" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Enurado Dungeon" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "The Tofuhouse" },
    { type: "Modulox 51 - 95", name: "Morbax Neplopolis" },
    { type: "Modulox 96 - 140", name: "The Frozen Tower" },
    { type: "Modulox 141 - 185", name: "The Zeppelantern" },
    { type: "Modulox 186 - 230", name: "Scramshell Dungeon" },
  ],
  "26/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Treechnid Dungeon" },
    { type: "DJ 141 - 155", name: "Wellspring of Evil" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Gobball Pastures" },
    { type: "Modulox 51 - 95", name: "Mussly Hammam" },
    { type: "Modulox 96 - 140", name: "Jelly Dungeon" },
    { type: "Modulox 141 - 185", name: "Blopera" },
    { type: "Modulox 186 - 230", name: "Necroworld" },
  ],
  "27/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Cwab's Castle" },
    { type: "DJ 66 - 80", name: "Lunar Altar" },
    { type: "DJ 81 - 95", name: "Miseryum" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "The Frozen Tower" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "The Minerall Tower (lvl 200)" },
    { type: "DJ 201 - 215", name: "Scramshell Dungeon" },
    { type: "DJ 216 - 230", name: "Destroyer Dungeon" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "Larventura" },
    { type: "Modulox 51 - 95", name: "Tsu's Palace" },
    { type: "Modulox 96 - 140", name: "Kween's Gawden" },
    { type: "Modulox 141 - 185", name: "Ow El Dungeon" },
    { type: "Modulox 186 - 230", name: "Plantiguard Dungeon" },
  ],
  "28/01/2026": [
    { type: "DJ 6 - 20", name: "??" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "The Ratatombs" },
    { type: "DJ 81 - 95", name: "Abandoned Scarapit" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "Puddly Dungeon" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "The Mineral Tower" },
    { type: "Modulox 51 - 95", name: "Trool Academy" },
    { type: "Modulox 96 - 140", name: "Magik Riktus Den" },
    { type: "Modulox 141 - 185", name: "The Villainy Vineyards" },
    { type: "Modulox 186 - 230", name: "Blightopard Canyon" },
  ],
  "29/01/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "The Forgotten Lair" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "Ambassador's Wing" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Or'Hodruin Volcano" },
    { type: "DJ 201 - 215", name: "Sunsloth Dungeon" },
    { type: "DJ 216 - 230", name: "Voidivion Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Octopus Crew Dungeon" },
    { type: "Modulox 51 - 95", name: "Mussly Hammam" },
    { type: "Modulox 96 - 140", name: "Hushquarters" },
    { type: "Modulox 141 - 185", name: "Enurado Dungeon" },
    { type: "Modulox 186 - 230", name: "Sunsloth Dungeon" },
  ],
  "30/01/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "Schnekymosis Cavern" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "The Hill Hazize" },
    { type: "Modulox 51 - 95", name: "Kokokobana" },
    { type: "Modulox 96 - 140", name: "Great Zomkin's Compost" },
    { type: "Modulox 141 - 185", name: "Bistrogue" },
    { type: "Modulox 186 - 230", name: "Or'Hodruin Volcano" },
  ],
  "31/01/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "Morbax Neplopolis" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Sandyoptera Mother-Hive" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "Hoola Hoopiwi" },
    { type: "Modulox 51 - 95", name: "Abandoned Scarapit" },
    { type: "Modulox 96 - 140", name: "Castuc Dungeon" },
    { type: "Modulox 141 - 185", name: "The Zeppelantern" },
    { type: "Modulox 186 - 230", name: "Vandalophrenic Dungeon" },
  ],
  "01/02/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Cwab's Castle" },
    { type: "DJ 66 - 80", name: "Abandoned Strichery" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Treechnid Dungeon" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Iced-Over Crest" },
    { type: "DJ 201 - 215", name: "Tundrazor Dungeon" },
    { type: "DJ 216 - 230", name: "Destroyer Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "The Tofuhouse" },
    { type: "Modulox 51 - 95", name: "Schnekymosis Cavern" },
    { type: "Modulox 96 - 140", name: "The Snaptrap" },
    { type: "Modulox 141 - 185", name: "Sandyoptera Mother-Hive" },
    { type: "Modulox 186 - 230", name: "Iced-Over Crest" },
  ],
  "02/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "Ambassador's Wing" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "The Minerall Tower (lvl 200)" },
    { type: "DJ 201 - 215", name: "Scramshell Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Gobball Pastures" },
    { type: "Modulox 51 - 95", name: "Mollusky Dungeon" },
    { type: "Modulox 96 - 140", name: "The Whirlway Station" },
    { type: "Modulox 141 - 185", name: "Kali's Lair" },
    { type: "Modulox 186 - 230", name: "Destroyer Dungeon" },
  ],
  "03/02/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "Enurado Dungeon" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "??" },
    { type: "Modulox 51 - 95", name: "Lunar Altar" },
    { type: "Modulox 96 - 140", name: "Hagen Daz's Pot" },
    { type: "Modulox 141 - 185", name: "Kannivore Dungeon" },
    { type: "Modulox 186 - 230", name: "The Minerall Tower (lvl 200)" },
  ],
  "04/02/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "Puddly Dungeon" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "Wellspring of Evil" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "" },
    { type: "Modulox 51 - 95", name: "The Undieworld" },
    { type: "Modulox 96 - 140", name: "Great Zomkin's Compost" },
    { type: "Modulox 141 - 185", name: "The Zeppelantern" },
    { type: "Modulox 186 - 230", name: "Voidivion Dungeon" },
  ],
  "05/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "Miseryum" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "" },
    { type: "Modulox 51 - 95", name: "Arachnee Dungeon" },
    { type: "Modulox 96 - 140", name: "Dancehall Arena" },
    { type: "Modulox 141 - 185", name: "Bistrogue" },
    { type: "Modulox 186 - 230", name: "Phytomorph Dungeon" },
  ],
  "06/02/2026": [
    { type: "DJ 6 - 20", name: "??" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "Abandoned Scarapit" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "" },
    { type: "Modulox 51 - 95", name: "Schnekymosis Cavern" },
    { type: "Modulox 96 - 140", name: "Flaxhid's Sanctuary" },
    { type: "Modulox 141 - 185", name: "Mecha Factory" },
    { type: "Modulox 186 - 230", name: "The Mineral Tower (lvl 215)" },
  ],
  "07/02/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Bworkana Clan Dungeon" },
    { type: "Modulox 6 - 50", name: "" },
    { type: "Modulox 51 - 95", name: "Trool Academy" },
    { type: "Modulox 96 - 140", name: "Tormentor Pit" },
    { type: "Modulox 141 - 185", name: "Crocodyl Dungeon" },
    { type: "Modulox 186 - 230", name: "Foggernaut Dungeon" },
  ],
  "08/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Schnekymosis Cavern" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "The Frozen Tower" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "" },
    { type: "Modulox 51 - 95", name: "The Ratatombs" },
    { type: "Modulox 96 - 140", name: "Dirty Trouffe Estate" },
    { type: "Modulox 141 - 185", name: "Forbidden City" },
    { type: "Modulox 186 - 230", name: "Crabstacean Dungeon" },
  ],
  "09/02/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Lunar Altar" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "" },
    { type: "Modulox 6 - 50", name: "??" },
    { type: "Modulox 51 - 95", name: "Cwab's Castle" },
    { type: "Modulox 96 - 140", name: "Puddly Dungeon" },
    { type: "Modulox 141 - 185", name: "Kali's Lair" },
    { type: "Modulox 186 - 230", name: "Abyssal Creeper Dungeon" },
  ],
  "10/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "Sandyoptera Mother-Hive" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "Larventura" },
    { type: "Modulox 51 - 95", name: "Lunar Altar" },
    { type: "Modulox 96 - 140", name: "Magik Riktus Den" },
    { type: "Modulox 141 - 185", name: "Elite Riktus Dungeon" },
    { type: "Modulox 186 - 230", name: "Horridemon Dungeon" },
  ],
  "11/02/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Bitter-Hammer Dungeon" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Forbidden City" },
    { type: "DJ 186 - 200", name: "Iced-Over Crest" },
    { type: "DJ 201 - 215", name: "Tundrazor Dungeon" },
    { type: "DJ 216 - 230", name: "Streye Dungeon?" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "The Tofuhouse" },
    { type: "Modulox 51 - 95", name: "Dry Selachii" },
    { type: "Modulox 96 - 140", name: "Moowolf's Lair" },
    { type: "Modulox 141 - 185", name: "Gerbean Dungeon" },
    { type: "Modulox 186 - 230", name: "Phytomorph Dungeon" },
  ],
  "12/02/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Cwab's Castle" },
    { type: "DJ 66 - 80", name: "Abandoned Strichery" },
    { type: "DJ 81 - 95", name: "Wagnar's Castle" },
    { type: "DJ 96 - 110", name: "Jelly Dungeon" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "Wa Wabbit's Castle" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "The Minerall Tower (lvl 200)" },
    { type: "DJ 201 - 215", name: "Scramshell Dungeon" },
    { type: "DJ 216 - 230", name: "Destroyer Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "Octopus Crew Dungeon" },
    { type: "Modulox 51 - 95", name: "Temple of the Grand Orrok" },
    { type: "Modulox 96 - 140", name: "Lenald Empelol's Temple" },
    { type: "Modulox 141 - 185", name: "Wellspring of Evil" },
    { type: "Modulox 186 - 230", name: "Iced-Over Crest" },
  ],
  "13/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Deathburn Dungeon" },
    { type: "DJ 51 - 65", name: "Mollusky Dungeon" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "The Undieworld" },
    { type: "DJ 96 - 110", name: "Magik Riktus Den" },
    { type: "DJ 111 - 125", name: "Ambassador's Wing" },
    { type: "DJ 126 - 140", name: "Treechnid Dungeon" },
    { type: "DJ 141 - 155", name: "Enurado Dungeon" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Pandala Tomb" },
    { type: "DJ 201 - 215", name: "Pingwin Dungeon" },
    { type: "DJ 216 - 230", name: "Foggernaut Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Hoola Hoopiwi" },
    { type: "Modulox 51 - 95", name: "Bwork Dungeon" },
    { type: "Modulox 96 - 140", name: "The Whirlway Station" },
    { type: "Modulox 141 - 185", name: "Ow El Dungeon" },
    { type: "Modulox 186 - 230", name: "Vandalophrenic Dungeon" },
  ],
  "14/02/2026": [
    { type: "DJ 6 - 20", name: "??" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Cro-Cave" },
    { type: "DJ 81 - 95", name: "Miseryum" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "The Whirlway Station" },
    { type: "DJ 126 - 140", name: "Dirty Trouffe Estate" },
    { type: "DJ 141 - 155", name: "Wellspring of Evil" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Gerbean Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Nox Machine Dungeon" },
    { type: "Modulox 6 - 50", name: "The Royal Pasturizer" },
    { type: "Modulox 51 - 95", name: "Mussly Hammam" },
    { type: "Modulox 96 - 140", name: "Hagen Daz's Pot" },
    { type: "Modulox 141 - 185", name: "Bistrogue" },
    { type: "Modulox 186 - 230", name: "The Mineral Tower (lvl 215)" },
  ],
  "15/02/2026": [
    { type: "DJ 6 - 20", name: "Larventura" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "Sureberry Fields" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Boarthroom Estate" },
    { type: "DJ 81 - 95", name: "Abandoned Scarapit" },
    { type: "DJ 96 - 110", name: "Hushquarters" },
    { type: "DJ 111 - 125", name: "Puddly Dungeon" },
    { type: "DJ 126 - 140", name: "Lenald Empelol's Temple" },
    { type: "DJ 141 - 155", name: "SrambadDungeon" },
    { type: "DJ 156 - 170", name: "The Stalagmotel" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "The Mineral Tower" },
    { type: "Modulox 51 - 95", name: "Arachnee Dungeon" },
    { type: "Modulox 96 - 140", name: "Flaxhid's Sanctuary" },
    { type: "Modulox 141 - 185", name: "Mecha Factory" },
    { type: "Modulox 186 - 230", name: "Abyssal Creeper Dungeon" },
  ],
  "16/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "Octopus Crew Dungeon" },
    { type: "DJ 51 - 65", name: "Dry Selachii" },
    { type: "DJ 66 - 80", name: "Tsu's Palace" },
    { type: "DJ 81 - 95", name: "Mussly Hammam" },
    { type: "DJ 96 - 110", name: "Moowolf's Lair" },
    { type: "DJ 111 - 125", name: "Tormentor Pit" },
    { type: "DJ 126 - 140", name: "Kween's Gawden" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "Mecha Factory" },
    { type: "DJ 171 - 185", name: "Tropickle Dungeon" },
    { type: "DJ 186 - 200", name: "Blightopard Canyon" },
    { type: "DJ 201 - 215", name: "Plantiguard Dungeon" },
    { type: "DJ 216 - 230", name: "Abyssal Creeper Dungeon" },
    { type: "DJ 231 - 245", name: "Starvannah Dungeon" },
    { type: "Modulox 6 - 50", name: "Sureberry Fields" },
    { type: "Modulox 51 - 95", name: "Tsu's Palace" },
    { type: "Modulox 96 - 140", name: "Jelly Dungeon" },
    { type: "Modulox 141 - 185", name: "Wa Wabbit's Castle" },
    { type: "Modulox 186 - 230", name: "Streye Dungeon?" },
  ],
  "17/02/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "The Raised Vault" },
    { type: "DJ 36 - 50", name: "The Mineral Tower" },
    { type: "DJ 51 - 65", name: "Kokokobana" },
    { type: "DJ 66 - 80", name: "Arachnee Dungeon" },
    { type: "DJ 81 - 95", name: "Schnekymosis Cavern" },
    { type: "DJ 96 - 110", name: "The Horned Glacier" },
    { type: "DJ 111 - 125", name: "Hagen Daz's Pot" },
    { type: "DJ 126 - 140", name: "Blackspore Dungeon" },
    { type: "DJ 141 - 155", name: "The Villainy Vineyards" },
    { type: "DJ 156 - 170", name: "Elite Riktus Dungeon" },
    { type: "DJ 171 - 185", name: "Kannivore Dungeon" },
    { type: "DJ 186 - 200", name: "Badgeroxes' Lair" },
    { type: "DJ 201 - 215", name: "Vandalophrenic Dungeon" },
    { type: "DJ 216 - 230", name: "Phytomorph Dungeon" },
    { type: "DJ 231 - 245", name: "Primount Dungeon" },
    { type: "Modulox 6 - 50", name: "Deathburn Dungeon" },
    { type: "Modulox 51 - 95", name: "Cwab's Castle" },
    { type: "Modulox 96 - 140", name: "Castuc Dungeon" },
    { type: "Modulox 141 - 185", name: "The Villainy Vineyards" },
    { type: "Modulox 186 - 230", name: "Pingwin Dungeon" },
  ],
  "18/02/2026": [
    { type: "DJ 6 - 20", name: "Gobball Pastures" },
    { type: "DJ 21 - 35", name: "Hoola Hoopiwi" },
    { type: "DJ 36 - 50", name: "The Hill Hazize" },
    { type: "DJ 51 - 65", name: "Miss Ugly Tower" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Morbax Neplopolis" },
    { type: "DJ 96 - 110", name: "Dancehall Arena" },
    { type: "DJ 111 - 125", name: "Castuc Dungeon" },
    { type: "DJ 126 - 140", name: "Great Zomkin's Compost" },
    { type: "DJ 141 - 155", name: "Blopera" },
    { type: "DJ 156 - 170", name: "Kali's Lair" },
    { type: "DJ 171 - 185", name: "Crocodyl Dungeon" },
    { type: "DJ 186 - 200", name: "Bubourg Factory" },
    { type: "DJ 201 - 215", name: "The Mineral Tower (lvl 215)" },
    { type: "DJ 216 - 230", name: "Necroworld" },
    { type: "DJ 231 - 245", name: "Ferociraptor Dungeon" },
    { type: "Modulox 6 - 50", name: "The Royal Pasturizer" },
    { type: "Modulox 51 - 95", name: "The Undieworld" },
    { type: "Modulox 96 - 140", name: "The Horned Glacier" },
    { type: "Modulox 141 - 185", name: "Enurado Dungeon" },
    { type: "Modulox 186 - 230", name: "Horridemon Dungeon" },
  ],
  "19/02/2026": [
    { type: "DJ 6 - 20", name: "The Tofuhouse" },
    { type: "DJ 21 - 35", name: "Treechnee Dungeon" },
    { type: "DJ 36 - 50", name: "The Royal Pasturizer" },
    { type: "DJ 51 - 65", name: "Bwork Dungeon" },
    { type: "DJ 66 - 80", name: "Temple of the Grand Orrok" },
    { type: "DJ 81 - 95", name: "Trool Academy" },
    { type: "DJ 96 - 110", name: "Supervillains' Lair" },
    { type: "DJ 111 - 125", name: "The Snaptrap" },
    { type: "DJ 126 - 140", name: "Flaxhid's Sanctuary" },
    { type: "DJ 141 - 155", name: "Abandoned Cawwot Stowewoom" },
    { type: "DJ 156 - 170", name: "The Zeppelantern" },
    { type: "DJ 171 - 185", name: "Kanniball Dungeon" },
    { type: "DJ 186 - 200", name: "Dreggons' Sanctuary" },
    { type: "DJ 201 - 215", name: "Crabstacean Dungeon" },
    { type: "DJ 216 - 230", name: "Horridemon Dungeon" },
    { type: "DJ 231 - 245", name: "Timeless Theater Dungeon" },
    { type: "Modulox 6 - 50", name: "Treechnee Dungeon" },
    { type: "Modulox 51 - 95", name: "The Ratatombs" },
    { type: "Modulox 96 - 140", name: "Kween's Gawden" },
    { type: "Modulox 141 - 185", name: "Forbidden City" },
    { type: "Modulox 186 - 230", name: "The Mineral Tower (lvl 215)" },
  ],
};

// ==========================================
// MULTILINGUAL TRANSLATION DICTIONARY
// ==========================================

const DUNGEON_TRANSLATIONS = {
  "Gobball Pastures": {
    en: "Gobball Pastures",
    fr: "Pâturages des Bouftous",
    es: "Pastos de los Jalatós",
    pt: "Pastagens dos Papatudos",
  },
  "The Raised Vault": {
    en: "The Raised Vault",
    fr: "Le Caveau Relevé",
    es: "Panteón Viviente",
    pt: "Tumba Levanta-Defunto",
  },
  "Deathburn Dungeon": {
    en: "Deathburn Dungeon",
    fr: "Donjon Mort-Brûlés",
    es: "Mazmorra Fallecinerados",
    pt: "Calabouço dos Mortos-Queimados",
  },
  "Mollusky Dungeon": {
    en: "Mollusky Dungeon",
    fr: "Donjon Mollusky",
    es: "Mazmorra Kaskarlusca",
    pt: "Calabouço do Molusky",
  },
  "Lunar Altar": {
    en: "Lunar Altar",
    fr: "Autel de la Lune",
    es: "Altar de la Luna",
    pt: "Altar Lunar",
  },
  "Mussly Hammam": {
    en: "Mussly Hammam",
    fr: "Le Hammamamoule",
    es: "El Hammalmejil",
    pt: "O Hammamexilhão",
  },
  "Magik Riktus Den": {
    en: "Magik Riktus Den",
    fr: "Repaire des Magik Riktus",
    es: "Guarida de los Magik Riktus",
    pt: "Covil dos Riktus Màgikus",
  },
  "The Snaptrap": {
    en: "The Snaptrap",
    fr: "La Pichine",
    es: "La Pischina",
    pt: "Pichina",
  },
  "Flaxhid's Sanctuary": {
    en: "Flaxhid's Sanctuary",
    fr: "Sanctuaire de Mihmol",
    es: "Santuario de Mihmol",
    pt: "Santuário de Meyduro",
  },
  "Wa Wabbit's Castle": {
    en: "Wa Wabbit's Castle",
    fr: "Château du Wa Wabbit",
    es: "Castillo del Wey Wabbit",
    pt: "Castelo do Wei Wabbit",
  },
  "Ow El Dungeon": {
    en: "Ow El Dungeon",
    fr: "Donjon E-Bou",
    es: "Donjon E-Bou",
    pt: "Calabouço E-Strigide",
  },
  "Kannivore Dungeon": {
    en: "Kannivore Dungeon",
    fr: "Donjon des Kannivores",
    es: "Mazmorra de las Kanívoras",
    pt: "Calabouço dos Kanívoros",
  },
  "Pandala Tomb": {
    en: "Pandala Tomb",
    fr: "Tombeau de Pandala",
    es: "Tumba de Pandala",
    pt: "Tumba de Pandala",
  },
  "Pingwin Dungeon": {
    en: "Pingwin Dungeon",
    fr: "Donjon Mansots",
    es: "Mazmorra de los Güinos",
    pt: "Calabouço dos Pingwins",
  },
  "Foggernaut Dungeon": {
    en: "Foggernaut Dungeon",
    fr: "Donjon Steamers",
    es: "Mazmorra Steamers",
    pt: "Calabouço dos Steamers",
  },
  "Primount Dungeon": {
    en: "Primount Dungeon",
    fr: "Donjon Primassifs",
    es: "Mazmorra de los Primacizos",
    pt: "Calabouço dos Primaciços",
  },
  "The Hill Hazize": {
    en: "The Hill Hazize",
    fr: "La Montagne Adezieu",
    es: "Montaña Conohos",
    pt: "Montanha Tenholios",
  },
  Miseryum: {
    en: "Miseryum",
    fr: "Le Misolée",
    es: "Miasmausoleo",
    pt: "O Mausaoléu",
  },
  "Enurado Dungeon": {
    en: "Enurado Dungeon",
    fr: "Donjon Enutrosor",
    es: "Mazmorra de Anutropía",
    pt: "Calabouço Enutropia",
  },
  "Plantiguard Dungeon": {
    en: "Plantiguard Dungeon",
    fr: "Donjon Plantigardes",
    es: "Mazmorra de los Plantiguardias",
    pt: "Calabouço dos Plantíguardas",
  },
  "Hoola Hoopiwi": {
    en: "Hoola Hoopiwi",
    fr: "Piou Lahoupe",
    es: "Pío Lajop",
    pt: "Piuibolê",
  },
  "The Royal Pasturizer": {
    en: "The Royal Pasturizer",
    fr: "Le Papaturage Royal",
    es: "Pasto Real",
    pt: "Pasteurizador Real",
  },
  "Bwork Dungeon": {
    en: "Bwork Dungeon",
    fr: "Donjon Bwork",
    es: "Donjon Bwork",
    pt: "Calabouço Bwork",
  },
  "Boarthroom Estate": {
    en: "Boarthroom Estate",
    fr: "Domaine du Petit Groin",
    es: "Domaine du Petit Groin",
    pt: "Domíno do Javaleiro",
  },
  "The Undieworld": {
    en: "The Undieworld",
    fr: "Sliptorium",
    es: "Sliptorium",
    pt: "Sliptorium",
  },
  Hushquarters: {
    en: "Hushquarters",
    fr: "Chuchobase",
    es: "Base de Susurro",
    pt: "Sussubase",
  },
  "Tormentor Pit": {
    en: "Tormentor Pit",
    fr: "Fosse du Tourmenteur",
    es: "Fosa del Atormentador",
    pt: "Fossa do Atormentador",
  },
  "Lenald Empelol's Temple": {
    en: "Lenald Empelol's Temple",
    fr: "Templo del Empeladol Zollo",
    es: "Templo del Empeladol Zollo",
    pt: "Templo do Laposa Impeladol",
  },
  Blopera: { en: "Blopera", fr: "Le Blopéra", es: "Blópera", pt: "Blópera" },
  "The Zeppelantern": {
    en: "The Zeppelantern",
    fr: "Le Lampionaute",
    es: "El Lampionaute",
    pt: "Zepelanterna",
  },
  "Crocodyl Dungeon": {
    en: "Crocodyl Dungeon",
    fr: "Donjon des Crocodailles",
    es: "Mazmorra de los Cocodrails Delnilo",
    pt: "Calabouço dos Crocodyls",
  },
  "Dreggons' Sanctuary": {
    en: "Dreggons' Sanctuary",
    fr: "Sanctuaire des Dragoeufs",
    es: "Santuario de los Dragohuevos",
    pt: "Santuário dos Dragovos",
  },
  "Crabstacean Dungeon": {
    en: "Crabstacean Dungeon",
    fr: "Donjon Crustrargneux",
    es: "Mazmorra Crustariscos",
    pt: "Calabouço dos Crustacirrados",
  },
  "Horridemon Dungeon": {
    en: "Horridemon Dungeon",
    fr: "Donjon Démhorribles",
    es: "Mazmorra de los Demorribles",
    pt: "Calabouço dos Demhorríveis",
  },
  "Ferociraptor Dungeon": {
    en: "Ferociraptor Dungeon",
    fr: "Donjon Férociraptors",
    es: "Mazmorra de los Ferocirraptores",
    pt: "Calabouço dos Ferociraptores",
  },
  "Sureberry Fields": {
    en: "Sureberry Fields",
    fr: "Les Champs Pourchan",
    es: "Campos Hupremos",
    pt: "Campos Frutocerto",
  },
  "The Stalagmotel": {
    en: "The Stalagmotel",
    fr: "La Patapoutrerie",
    es: "La Patapoutrerie",
    pt: "O Estalagmotel",
  },
  "Destroyer Dungeon": {
    en: "Destroyer Dungeon",
    fr: "Donjon Ravageurs",
    es: "Mazmorra de los Devastadores",
    pt: "Calabouço dos Devastadores",
  },
  "The Tofuhouse": {
    en: "The Tofuhouse",
    fr: "Le Tofulailler",
    es: "Tofullero",
    pt: "O Tofuleiro",
  },
  "The Mineral Tower": {
    en: "The Mineral Tower",
    fr: "La Tour Minérale",
    es: "La Torre Mineral",
    pt: "Torre Mineral",
  },
  "Dry Selachii": {
    en: "Dry Selachii",
    fr: "La Skouale Sèche",
    es: "Dique Eskuálido",
    pt: "Tchubarco",
  },
  "Cro-Cave": {
    en: "Cro-Cave",
    fr: "La Corbeau-Cave",
    es: "La Corbeau-Cave",
    pt: "Corvocaverna",
  },
  "Morbax Neplopolis": {
    en: "Morbax Neplopolis",
    fr: "Nécropoil de Morbax",
    es: "Necrópelis de Morbax",
    pt: "Necrópelos de Morbax",
  },
  "Supervillains' Lair": {
    en: "Supervillains' Lair",
    fr: "Repaire des Super-Vilains",
    es: "Guarida de los Supervillanos",
    pt: "Covil dos Supervilöes",
  },
  "Castuc Dungeon": {
    en: "Castuc Dungeon",
    fr: "Donjon Cacterre",
    es: "Mazmorra Cacterra",
    pt: "Calabouço Cacterra",
  },
  "Dirty Trouffe Estate": {
    en: "Dirty Trouffe Estate",
    fr: "Domaine de la Trouffe Salée",
    es: "Hacienda de la Topera Oculta",
    pt: "Domínio da Perfuratrocidade",
  },
  SrambadDungeon: {
    en: "SrambadDungeon",
    fr: "Donjon Srambad",
    es: "Mazmorra Sramvil",
    pt: "Calabouço Sramvil",
  },
  "Kali's Lair": {
    en: "Kali's Lair",
    fr: "Repaire de Kali",
    es: "Guarida de Kali",
    pt: "Covil de Kali",
  },
  "Kanniball Dungeon": {
    en: "Kanniball Dungeon",
    fr: "Donjon des Kannibouls",
    es: "Mazmorra Kaníbola",
    pt: "Calabouço dos Kanibolas",
  },
  "Blightopard Canyon": {
    en: "Blightopard Canyon",
    fr: "Canyon des Fléopards",
    es: "Cañón de los Plaguepardos",
    pt: "Cânion dos Flagelopardos",
  },
  "Abyssal Creeper Dungeon": {
    en: "Abyssal Creeper Dungeon",
    fr: "Donjon Poisseux Abyssaux",
    es: "Mazmorra Pezgajosos Abisales",
    pt: "Calabouço dos Pescajosos Abissais",
  },
  "Timeless Theater Dungeon": {
    en: "Timeless Theater Dungeon",
    fr: "Théâtre intemporel",
    es: "Mazmorra del Teatro Intemporal",
    pt: "Calabouço Teatro Atemporal",
  },
  Larventura: {
    en: "Larventura",
    fr: "Larventura",
    es: "Larventura",
    pt: "Larventura",
  },
  "Treechnee Dungeon": {
    en: "Treechnee Dungeon",
    fr: "Donjon des Abraknes",
    es: "Mazmorra Abrakna",
    pt: "Calabouço dos Arvraknes",
  },
  "Octopus Crew Dungeon": {
    en: "Octopus Crew Dungeon",
    fr: "Donjon équipage du Poulpe",
    es: "Mamorra Tripulación del Pulpo",
    pt: "Calabouço Tripulação do Polvo",
  },
  "Bitter-Hammer Dungeon": {
    en: "Bitter-Hammer Dungeon",
    fr: "Donjon Marteaux-Aigris",
    es: "Mazmorra Martilloseco",
    pt: "Calabouço dos Martelos Amargos",
  },
  "Arachnee Dungeon": {
    en: "Arachnee Dungeon",
    fr: "Donjon Arakne",
    es: "Donjon Arakne",
    pt: "Calabouço Arakne",
  },
  "Trool Academy": {
    en: "Trool Academy",
    fr: "La Trool Academy",
    es: "La Trool Academy",
    pt: "Academia Trool",
  },
  "Jelly Dungeon": {
    en: "Jelly Dungeon",
    fr: "Donjon Gelée",
    es: "Mazmorra Gelatinada",
    pt: "Calabouço de Gelatina",
  },
  "Hagen Daz's Pot": {
    en: "Hagen Daz's Pot",
    fr: "Le Pot d'Hagën-Glass",
    es: "Cono de Crújian Jerry",
    pt: "Pote de Quibom",
  },
  "Great Zomkin's Compost": {
    en: "Great Zomkin's Compost",
    fr: "Compost du grand Potofeu",
    es: "Compost del Gran Calabaciflor",
    pt: "Composteira do Grande Cozidim",
  },
  "Abandoned Cawwot Stowewoom": {
    en: "Abandoned Cawwot Stowewoom",
    fr: "Despensa de Cenouwa Abandonada",
    es: "Despensa de Cenouwa Abandonada",
    pt: "Despensa de Cenouwa Abandonada",
  }, // Note: Kept consistent across ES/PT based on HTML provided, though looks untranslated in HTML
  Bistrogue: {
    en: "Bistrogue",
    fr: "Roub'Bar",
    es: "Tymabar",
    pt: "Ladinobar",
  },
  "Forbidden City": {
    en: "Forbidden City",
    fr: "Cité Interdite",
    es: "Ciudad Prohibida",
    pt: "Cidade Proibida",
  },
  "Iced-Over Crest": {
    en: "Iced-Over Crest",
    fr: "La Crête Givrée",
    es: "Cresta Helada",
    pt: "Crista Congelada",
  },
  "Tundrazor Dungeon": {
    en: "Tundrazor Dungeon",
    fr: "Donjon Toundrasoirs",
    es: "Mazmorra Nievajas",
    pt: "Calabouço dos Tundrafiados",
  },
  "Streye Dungeon?": {
    en: "Streye Dungeon?",
    fr: "Donjon Égarés ?",
    es: "Mazmorra de los Idos",
    pt: "Calabouço dos Perdidos",
  },
  "Starvannah Dungeon": {
    en: "Starvannah Dungeon",
    fr: "Donjon Savanastraux",
    es: "Mazmorra de los Sabanastrales",
    pt: "Calabouço Savanastral",
  },
  "Ambassador's Wing": {
    en: "Ambassador's Wing",
    fr: "Ala da Embaixatriz",
    es: "Ala de la Embajadora",
    pt: "Ala da Embaixatriz",
  },
  "Moowolf's Lair": {
    en: "Moowolf's Lair",
    fr: "Antro do Mulobo",
    es: "Antro de Maxilubo",
    pt: "Antro do Mulobo",
  },
  "Gerbean Dungeon": {
    en: "Gerbean Dungeon",
    fr: "Donjon Gerbouille",
    es: "Mazmorra Gerbilinda",
    pt: "Calabouço Gerbela",
  },
  "Phytomorph Dungeon": {
    en: "Phytomorph Dungeon",
    fr: "Donjon Phytomorphes",
    es: "Mazmorra de los Fitoformes",
    pt: "Calabouço dos Fitomorfos",
  },
  "The Forgotten Lair": {
    en: "The Forgotten Lair",
    fr: "L'Antre Oubliée",
    es: "Antro Olvidado",
    pt: "Antro Esquecido",
  },
  "The Ratatombs": {
    en: "The Ratatombs",
    fr: "Les Ratacombes",
    es: "The Ratatombs",
    pt: "As Ratatumbas",
  },
  "Wagnar's Castle": {
    en: "Wagnar's Castle",
    fr: "Château de Wagnar",
    es: "Castillo de Wagnar",
    pt: "Castelo de Wagnar",
  },
  "The Whirlway Station": {
    en: "The Whirlway Station",
    fr: "Caverne Smarrante",
    es: "Cavernia Samaraciosa",
    pt: "Caverna Turbilária",
  },
  "The Villainy Vineyards": {
    en: "The Villainy Vineyards",
    fr: "Le Vignoble Ignoble",
    es: "Le Vignoble Ignoble",
    pt: "Vinhedo Azedo",
  },
  "The Stalagmotel": {
    en: "The Stalagmotel",
    fr: "La Patapoutrerie",
    es: "La Patapoutrerie",
    pt: "O Estalagmotel",
  },
  "Or'Hodruin Volcano": {
    en: "Or'Hodruin Volcano",
    fr: "Volcan Or'Hodruin",
    es: "Volcán Or'Hodruin",
    pt: "Vulcão Or'Hodruin",
  },
  "Sunsloth Dungeon": {
    en: "Sunsloth Dungeon",
    fr: "Donjon Cagnardeurs",
    es: "Mazmorra Solgazanes",
    pt: "Calabouço dos Estorritardos",
  },
  "Voidivion Dungeon": {
    en: "Voidivion Dungeon",
    fr: "Donjon Vidéants",
    es: "Mazmorra de los Vaciantes",
    pt: "Calabouço dos Vaziantes",
  },
  "Treechnid Dungeon": {
    en: "Treechnid Dungeon",
    fr: "Donjon Abraknyde",
    es: "Mazmorra Abráknida",
    pt: "Calabouço Arvraknídeo",
  },
  "Elite Riktus Dungeon": {
    en: "Elite Riktus Dungeon",
    fr: "Donjon Riktus Elite",
    es: "Donjon Riktus Elite",
    pt: "Calabouço Riktus de Elite",
  },
  "The Minerall Tower (lvl 200)": {
    en: "The Minerall Tower (lvl 200)",
    fr: "La Tour Minérale Elite (lvl 200)",
    es: "La Torre Mineral (lvl 200)",
    pt: "Torre Mineral (lvl 200)",
  },
  "Miss Ugly Tower": {
    en: "Miss Ugly Tower",
    fr: "Tour des Miss Moches",
    es: "Torre de las Miss Adefesio",
    pt: "Torre das Miss Feias",
  },
  "Temple of the Grand Orrok": {
    en: "Temple of the Grand Orrok",
    fr: "Temple du Grand Orrok",
    es: "Templo del Gran Orrok",
    pt: "Templo do Grande Orrok",
  },
  "Abandoned Scarapit": {
    en: "Abandoned Scarapit",
    fr: "Scarrière Abandonnée",
    es: "Escarantera Abandonada",
    pt: "Scaranteira Abandonada",
  },
  "The Frozen Tower": {
    en: "The Frozen Tower",
    fr: "La tour Gelée",
    es: "Torre Helada",
    pt: "A Torre Congelada",
  },
  "Blackspore Dungeon": {
    en: "Blackspore Dungeon",
    fr: "Donjon Noirespore",
    es: "Mazmorra Negraspora",
    pt: "Calabouço Negresporo",
  },
  "Nox Machine Dungeon": {
    en: "Nox Machine Dungeon",
    fr: "Donjon Machines de Nox",
    es: "Mazmorra Máquinas de Nox",
    pt: "Calabouço Máquinas de Nox",
  },
  "Abandoned Strichery": {
    en: "Abandoned Strichery",
    fr: "Truchière Abandonnée",
    es: "Pestrucería Abandonada",
    pt: "Truzeria Abandonada",
  },
  "Scramshell Dungeon": {
    en: "Scramshell Dungeon",
    fr: "Donjon Carapattes",
    es: "Mazmorra de los Escapatarazones",
    pt: "Calabouço dos Carapatas",
  },
  Kokokobana: {
    en: "Kokokobana",
    fr: "Kokokolantha",
    es: "Kokolost Island",
    pt: "Kokokobana",
  },
  "Schnekymosis Cavern": {
    en: "Schnekymosis Cavern",
    fr: "Caverne des Slekymoses",
    es: "Cavernia Brizlónica",
    pt: "Caverna das Vermugas",
  },
  "Mecha Factory": {
    en: "Mecha Factory",
    fr: "Fabrique Méka",
    es: "Mekafábrica",
    pt: "Fábrica Meka",
  },
  "Tropickle Dungeon": {
    en: "Tropickle Dungeon",
    fr: "Donjon des Tropikes",
    es: "Mazmorra de los Trópipikos",
    pt: "Calabouço dos Trópikos",
  },
  "Badgeroxes' Lair": {
    en: "Badgeroxes' Lair",
    fr: "Tanière des Blérox",
    es: "Guarida de los Tejaroxores",
    pt: "Toca dos Texox",
  },
  "Vandalophrenic Dungeon": {
    en: "Vandalophrenic Dungeon",
    fr: "Donjon Vandaliénés",
    es: "Mazmorra Vandalienados",
    pt: "Calabouço dos Vandalienados",
  },
  "Bworkana Clan Dungeon": {
    en: "Bworkana Clan Dungeon",
    fr: "Donjon Clan de Bworkana",
    es: "Mazmorra del Clan de Bworkana",
    pt: "Calabouço Clã de Bworkana",
  },
  Necroworld: {
    en: "Necroworld",
    fr: "Nécromonde",
    es: "Necromundo",
    pt: "Necromundo",
  },
  "Tsu's Palace": {
    en: "Tsu's Palace",
    fr: "Palais du Tsu",
    es: "Palacio de Tsu",
    pt: "Palácio de Csé",
  },
  "Bubourg Factory": {
    en: "Bubourg Factory",
    fr: "Usine Hibourg",
    es: "Fábrica Buhatrás",
    pt: "Fábrica Strigifrent",
  },
  "Sandyoptera Mother-Hive": {
    en: "Sandyoptera Mother-Hive",
    fr: "Ruche-mère Sabléoptère",
    es: "Colmena Madre Arenóptera",
    pt: "Colmeia-Mãe dos Areiópteros",
  },
  "The Ratatombs": {
    en: "The Ratatombs",
    fr: "Les Ratacombes",
    es: "Las Ratatumbas",
    pt: "As Ratatumbas",
  },
  "Kween's Gawden": {
    en: "Kween's Gawden",
    fr: "Jardin de la Reine",
    es: "Jardín de la Reina",
    pt: "Jardim da Rainha",
  },
  "Wellspring of Evil": {
    en: "Wellspring of Evil",
    fr: "Source du Mal",
    es: "Fuente del Mal",
    pt: "Origem do Mal",
  },
};
